fail_fast: true

repos:
  - repo: local
    hooks:
      - id: poetry
        name: poetry
        entry: poetry update
        language: system
        types: [file, python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: reformat
        name: reformat
        entry: make reformat
        language: system
        types: [file, python]
        pass_filenames: false
